name: Node CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: Create artifact folder
      run: mkdir -p dist/

    - name: Compile
      run: npm run build

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v1
      with:
        name: 'tonichaz_gh.tar.gz'
        path: dist/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist
